# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lnglate',
            field=models.CharField(blank=True, help_text='위도/경도 포멧으로 입력하시오', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='제목을 입력하시오. 최대 100자 내외', max_length=100, verbose_name='제목'),
        ),
    ]
