# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 13:29
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180516_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lnglate',
        ),
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도/위도 포멧으로 입력하시오', max_length=50, validators=[blog.models.lnglat_validator]),
        ),
    ]
