# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180516_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Anonymous', max_length=20, verbose_name='작성자'),
            preserve_default=False,
        ),
    ]
